name: Build project
on: push

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Setup

      - name: Validate
        run:
          make validate

      - name: Unit Tests
        run:
          make unit-tests

      - name: Integration tests
        run:
          make integration-tests